### ISSUE TITLE
Camperbot fails to give points if the username is camelcased

### ISSUE THREAD

**Issue by oppiniated** [FreeCodeCamp/camperbot#116]
In the instance if the username is camel cased for eg **EastML**, the camperbot tries to give points to usernmae **eastml** and fails to find such user 

[![error](https://s15.postimg.org/7bpx6szzf/Screen_Shot_2016_11_10_at_1_46_09_PM.png)](https://postimg.org/image/y9ju8jkmf/)

**Comment by abhisekp** [comment]
Thanks for reporting.

The user must link their Github profile to FreeCodeCamp so that @camperbot can get their information.

@oppiniated Please provide them the link https://www.freecodecamp.com/link/github to link their github profile to FreeCodeCamp.

----
The user with uppercase username is able get points.

> [![uppercased username](http://i.imgur.com/ekFrs61.png)](http://i.imgur.com/ekFrs61.png)
