### ISSUE TITLE
Remove/Improve "Add a Wiki" response

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/camperbot#32]
Right now if you search for something using the `wiki` command and it's not found you get a message like this:
![image](https://cloud.githubusercontent.com/assets/553494/11858439/6dab985c-a416-11e5-9d31-98c53ce33f72.png)
The URL is no longer valid because we turned off the main Wiki commits.  Now you need to go through the PR process on the main Wiki.

Maybe we need an article on how to add articles?  Anyway, we need to remove this message for now.

**Comment by ltegman** [comment]
Closing this as a PR was merged to remove the message.

**Comment by dcsan** [comment]
you might wanna leave it open as its really unclear now how to add wiki content. 
have meaningful updates died off?

https://github.com/FreeCodeCamp/wiki/commits/master?page=3
most of these seem to be adding cities in the last month.

**Comment by dcsan** [comment]
related discussion

hey can i ask what's the setup for adding new wiki entries for camperbot nowadays? did you close that down due to spam issues?

BerkeleyTrue 19:08
@dcsan Yes
You can create new entries by forming PR against the wiki repo

dcsan 19:09
got it

BerkeleyTrue 19:09
github.com/freecodecamp/wiki

dcsan 19:09
so its a real repo, not a github wiki?

BerkeleyTrue 19:09
yup

dcsan 19:09
got it
btw i'm using docpad for another app
its a SSG and you can use it to serve up/build markdown wikis pretty easily
maybe good to expose all that FCC wiki content actually on your main site too...
could be a good SEO honeypot, better than that W3C crap...

SaintPeter 19:11
@dcsan We've got a script to convert the Wiki pages into a "Real" website via Gatsby, but it needs a bit of tuning before it can be live.

dcsan 19:12
got it. probly a better choice for you guys.
i'm serving to mobile so wanted to have as minimal JS as possible.. no react
tempting tho
is that going to be editable tho?
is there an editor component? or just sticking with github for that?

SaintPeter 19:13
@dcsan I think we'll continue to use PRs and GitHub - it adds friction but increases quality

dcsan 19:13
one thing maybe nice is if people could somehow propose additions to the wiki thru chat ... and go into a simple "question / answer" mode
is there much activity? is the friction too high?
maybe you could put a trigger/hint back into camperbot with the wiki URL and an explanation...
explain recursion
oh, the bots not here?

SaintPeter 19:21
I think it's too high of friction. I've been pondering using the Wiki on the wiki to allow new articles. Pull them down and remove them when they're added .. . dunno.

**Comment by raisedadead** [comment]
Closing as a wontfix.
https://github.com/FreeCodeCamp/camperbot/issues/103
